In [2]:
import pandas as pd
import requests
import numpy as np

In [3]:
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/154.0.0.0 Safari/537.36 Edg/154.0.0.0"
}

res = requests.get(
    "https://gymkhana.iitb.ac.in/instiapp/api/mess",
    headers=headers,
    timeout=15
)

print(res.status_code)
print(res.text)

200

In [4]:
data=res.text

In [5]:
import json
parsed_data=json.loads(data)
with open('a.json','w') as f:
    json.dump(parsed_data,f,indent=4)

In [6]:
data=parsed_data

In [7]:
for i in data:
    print(i['name'])

Hostel 1
Hostel 10
Hostel 11
Hostel 12
Hostel 13
Hostel 14
Hostel 15
Hostel 16
Hostel 17
Hostel 18
Hostel 19
Hostel 2
Hostel 21
Hostel 3
Hostel 4
Hostel 5
Hostel 6
Hostel 7
Hostel 8
Hostel 9
QIP
Tansa

In [8]:
import os

In [42]:

import pandas as pd
import os

a = []
columns = ['hostel_name', 'day', 'item_name', 'meal']

for i in data[1:]:
    hostel_name = i['name']

    for j in i['mess']:
        day = j['day']

        for meal in ['breakfast', 'lunch', 'snacks', 'dinner']:
            items = j[meal].split(',')

            for item in items:
                item = item.strip()

                if item:
                    a.append([
                        hostel_name,
                        day,
                        item,
                        meal
                    ])

df = pd.DataFrame(a, columns=columns)

folder = os.path.join(os.getcwd(), 'mess_menus')
os.makedirs(folder, exist_ok=True)

df.to_csv(
    os.path.join(folder, 'all_hostel_menus.csv'),
    index=False
)

print("All hostel menus saved!")
print(df.head())

All hostel menus saved!
  hostel_name  day           item_name       meal
0   Hostel 10    7  Onion Methi Thepla  breakfast
1   Hostel 10    7      Tomato Chutney  breakfast
2   Hostel 10    7         Mix Sprouts  breakfast
3   Hostel 10    7                Milk  breakfast
4   Hostel 10    7         Tea /Coffee  breakfast

In [36]:
df=pd.read_csv('C:/Users/Anil/Downloads/MessMetrics/backend-fastapi/mess_menus/all_hostel_menus.csv')

In [38]:
df_modified = (
    df.groupby('item_name')[['meal', 'hostel_name', 'day']]
      .agg(lambda x: ', '.join(x.astype(str).unique()))
      .reset_index()
)

In [39]:
df_modified

,item_name,meal,hostel_name,day
0,(Cold Milk)/(Carrot,breakfast,"Hostel 12, Hostel 13, Hostel 14",2
1,3 Piece,dinner,Hostel 18,5
2,Aam Ras; Even Week: Rice,lunch,Hostel 11,7
3,Aamrus,lunch,Hostel 11,7
4,Achaari Gobi,dinner,Hostel 11,1
...,...,...,...,...
1075,dal fry,dinner,Hostel 3,5
1076,dal pakwan\nchutney\nMatki Sprouts\nBBJ\nMilk\...,breakfast,Hostel 5,2
1077,hot dog \nWatermelon\nBBJ\nTea/Coffee,snacks,Hostel 5,7
1078,tomato Rice\r\nDal Fry\r\nMethi Matar Masala\r...,lunch,Hostel 5,6
1079,tomato Rice\r\nMoong Dal\r\nHandi Paneer\r\nKa...,dinner,Hostel 5,6

In [41]:
df_modified.to_csv(os.path.join(folder, 'all_hostel_menus_1.csv'),index=False)

In [ ]:
hostels=[]
for i in data:
    hostels.append(i['name'])
meals = ['lunch', 'dinner','snacks','breakfast']

filtered = df[
    df['hostel_name'].isin(hostels) &
    df['meal'].str.lower().isin(meals)
].copy()

filtered['item_name'] = filtered['item_name'].str.strip().str.lower()

# Count how many distinct hostels serve each item per meal
common_items = (
    filtered.groupby(['meal', 'item_name'])['hostel_name']
    .nunique()
    .reset_index(name='hostel_count')
)

In [15]:
df3=pd.DataFrame(common_items)

In [16]:
df3

,meal,item_name,hostel_count
0,breakfast,(cold milk)/(carrot,3
1,breakfast,aloo bhaji,2
2,breakfast,aloo chana bhaji,1
3,breakfast,aloo paratha,5
4,breakfast,aloo paratha\ncurd/tomato chutney\negg bhurji\...,1
...,...,...,...
1208,snacks,veg sandwich,1
1209,snacks,veg. hakka noodles,1
1210,snacks,white pasta,1
1211,snacks,white sauce pasta,1
1212,snacks,white sauce pasta (olives+corn),1

In [79]:
df_reset = df.reset_index()
df_reset

,Day,breakfast,lunch,snacks,dinner
0,1,"Aloo Paratha, Curd, Pickle, Sprouts Moong, Cho...","Aloo Matar, Roti, Tomato Rice, Moong+Masoor Da...","Maggie, Milk, Tea, Coffee, Bbj, Bournvita, Fruit","Lauki Kofta, Rice, Toor Dal, Roti, Salad, Ras ..."
1,2,"Poha+Shiv+Chutney, Nimbu, Boiled Peanut, Choco...","Veg. Manchurian & Rajama, Dal Tadka, Rice, Sal...","Sprouts Chaat, Milk, Tea, Coffee, Bbj, Bournvi...","Sarso Ka Saag, Roti, Akha Masoor Dal, Pulav Ri..."
2,3,"Meduvada+Sambhar+ Chutney, Kala Chana, Chocos ...","Pumpkin Masala, Puri, Mix Dal, Rice, Papad, Sa...","Aloo Tikki+ Ragada & Chutney, Milk, Tea, Coffe...","Palak Paneer, Roti, Toor Dal, Rice, Roti, Sala..."
3,4,"Uttapam+Sambhar+ Chutney, Sprouts Matki, Choco...","Tinda Veg. Roti, Moong Dal, Biryani, Lijjat Pa...","Chole Kulche, Milk, Tea, Coffee, Bbj, Bournvita","Mushroom Gravy, Rice, Masoor Dal, Roti, Salad,..."
4,5,"Methi Thepla, Sweet Corn, Chocos + Cornflakes,...","Matar Paneer, Roti, Peas Rice, Dal, Salad, Chaa","Pav Bhaji + Nimbu, Milk, Tea, Coffee, Bbj, Bou...","Sev Tamatar & Aloo Beans, Rice, Toor Dal, Roti..."
5,6,"Sabudana Khichadi, Curd, Pickle, Sweet Corn, C...","Choole Bhature, Toor Dal, Rice, Salad, Papad, ...","Cheese Burger+ Salad, Milk, Tea, Coffee, Bbj, ...","Palak Methi Saag, Roti, Rice, Mix Dal, Salad, ..."
6,7,"Moong Dal Chilla Chutney, Sprouts Matki, Choco...","Misel Pov, Bread, Peanut Butter & Mix Jam, Tea...","Samosa Chutney, Milk, Tea, Coffee, Bbj, Bournv...","Kadi Pakoda & Kala Chana, Roti, Rice, Roti, Ak..."

In [62]:
df.iloc[:,0:df.shape[1]]

,breakfast,lunch,snacks,dinner
Day,,,,
1,"Aloo Paratha, Curd, Pickle, Sprouts Moong, Cho...","Aloo Matar, Roti, Tomato Rice, Moong+Masoor Da...","Maggie, Milk, Tea, Coffee, Bbj, Bournvita, Fruit","Lauki Kofta, Rice, Toor Dal, Roti, Salad, Ras ..."
2,"Poha+Shiv+Chutney, Nimbu, Boiled Peanut, Choco...","Veg. Manchurian & Rajama, Dal Tadka, Rice, Sal...","Sprouts Chaat, Milk, Tea, Coffee, Bbj, Bournvi...","Sarso Ka Saag, Roti, Akha Masoor Dal, Pulav Ri..."
3,"Meduvada+Sambhar+ Chutney, Kala Chana, Chocos ...","Pumpkin Masala, Puri, Mix Dal, Rice, Papad, Sa...","Aloo Tikki+ Ragada & Chutney, Milk, Tea, Coffe...","Palak Paneer, Roti, Toor Dal, Rice, Roti, Sala..."
4,"Uttapam+Sambhar+ Chutney, Sprouts Matki, Choco...","Tinda Veg. Roti, Moong Dal, Biryani, Lijjat Pa...","Chole Kulche, Milk, Tea, Coffee, Bbj, Bournvita","Mushroom Gravy, Rice, Masoor Dal, Roti, Salad,..."
5,"Methi Thepla, Sweet Corn, Chocos + Cornflakes,...","Matar Paneer, Roti, Peas Rice, Dal, Salad, Chaa","Pav Bhaji + Nimbu, Milk, Tea, Coffee, Bbj, Bou...","Sev Tamatar & Aloo Beans, Rice, Toor Dal, Roti..."
6,"Sabudana Khichadi, Curd, Pickle, Sweet Corn, C...","Choole Bhature, Toor Dal, Rice, Salad, Papad, ...","Cheese Burger+ Salad, Milk, Tea, Coffee, Bbj, ...","Palak Methi Saag, Roti, Rice, Mix Dal, Salad, ..."
7,"Moong Dal Chilla Chutney, Sprouts Matki, Choco...","Misel Pov, Bread, Peanut Butter & Mix Jam, Tea...","Samosa Chutney, Milk, Tea, Coffee, Bbj, Bournv...","Kadi Pakoda & Kala Chana, Roti, Rice, Roti, Ak..."

In [77]:
for i in df.iloc[:,-1]:
    print(i.split(','))

['Lauki Kofta', ' Rice', ' Toor Dal', ' Roti', ' Salad', ' Ras Malai', ' Fish']
['Sarso Ka Saag', ' Roti', ' Akha Masoor Dal', ' Pulav Rice', ' Salad', ' Gulab Jamun']
['Palak Paneer', ' Roti', ' Toor Dal', ' Rice', ' Roti', ' Salad', ' Bajra Kheer']
['Mushroom Gravy', ' Rice', ' Masoor Dal', ' Roti', ' Salad', ' Ice-Cream']
['Sev Tamatar & Aloo Beans', ' Rice', ' Toor Dal', ' Roti', ' Salad', ' Moong Dal Halwa', ' Chicken Curry']
['Palak Methi Saag', ' Roti', ' Rice', ' Mix Dal', ' Salad', ' Gajar Ka Halwa']
['Kadi Pakoda & Kala Chana', ' Roti', ' Rice', ' Roti', ' Akhaa Masoor Dal', ' Salad', ' Fruit Custard']

In [45]:
df=pd.read_csv('C:/Users/Anil/Downloads/MessMetrics/backend-fastapi/mess_menus/all_hostel_menus.csv')

In [46]:
df.head()

  hostel_name  day           item_name       meal
0   Hostel 10    7  Onion Methi Thepla  breakfast
1   Hostel 10    7      Tomato Chutney  breakfast
2   Hostel 10    7         Mix Sprouts  breakfast
3   Hostel 10    7                Milk  breakfast
4   Hostel 10    7         Tea /Coffee  breakfast

In [63]:
from pymongo import MongoClient
uri = "mongodb+srv://roopabhi07:12345@cluster0.pbbsvjb.mongodb.net/"
client = MongoClient(uri)
try:
    client.admin.command("ping")
    print("Connected successfully")
    client.close()

except Exception as e:
    raise Exception(
        "The following error occurred: ", e)

Exception: ('The following error occurred: ', ServerSelectionTimeoutError("SSL handshake failed: ac-qrjzhwi-shard-00-02.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-qrjzhwi-shard-00-00.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-qrjzhwi-shard-00-01.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6ad203b8fbb062d0b48e916e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-qrjzhwi-shard-00-00.pbbsvjb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-qrjzhwi-shard-00-00.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qrjzhwi-shard-00-01.pbbsvjb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-qrjzhwi-shard-00-01.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-qrjzhwi-shard-00-02.pbbsvjb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-qrjzhwi-shard-00-02.pbbsvjb.mongodb.net:27017: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>"))

In [64]:
pip install openai

Collecting openai
  Obtaining dependency information for openai from https://files.pythonhosted.org/packages/69/22/66014c8fede0aa2b3381cf80c5102219b78657b3e61776cdab8f0b78675a/openai-3.31.0-py3-none-any.whl.metadata
  Downloading openai-3.31.0-py3-none-any.whl.metadata (44 kB)
     ---------------------------------------- 0.0/44.3 kB ? eta -:--:--
     ---------------------------------------- 44.3/44.3 kB 2.1 MB/s eta 0:00:00
Collecting anyio<5,>=4.10.0 (from openai)
  Obtaining dependency information for anyio<5,>=4.10.0 from https://files.pythonhosted.org/packages/12/b8/4bd346e22b28902df4d651910f5242c28d84e4a5c2435ca5c3f797ed7e2e/anyio-4.15.1-py3-none-any.whl.metadata
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting httpx2<3,>=2.12.0 (from openai)
  Obtaining dependency information for httpx2<3,>=2.12.0 from https://files.pythonhosted.org/packages/d8/9c/6fe8931fd9f381042a9e4c7d5a7b4cbf7016b252bec0c99a49fce42c3326/httpx2-2.13.1-py3-none-any.whl.metadata
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Collecting jiter<1,>=0.16.0 (from openai)
  Obtaining dependency information for jiter<1,>=0.16.0 from https://files.pythonhosted.org/packages/6c/d9/98265a005b2473ec2be5a84e2b64c2f65382c673879f1574845cd4bcd77c/jiter-0.17.0-cp312-cp312-win_amd64.whl.metadata
  Downloading jiter-0.17.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Collecting pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13 (from openai)
  Obtaining dependency information for pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13 from https://files.pythonhosted.org/packages/35/ea/a56b9fe5066f3537b7882f77e9c5dfb26d8c2eefdaed9b5fc73d57b4dc22/pydantic-2.14.1-py3-none-any.whl.metadata
  Downloading pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
     ---------------------------------------- 0.0/133.0 kB ? eta -:--:--
     ----------------------------------- -- 122.9/133.0 kB 3.6 MB/s eta 0:00:01
     -------------------------------------- 133.0/133.0 kB 2.6 MB/s eta 0:00:00
Collecting sniffio (from openai)
  Obtaining dependency information for sniffio from https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl.metadata
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions<5,>=4.14 in c:\users\anil\downloads\messmetrics\backend-fastapi\.venv\lib\site-packages (from openai) (4.16.0)
Requirement already satisfied: idna>=2.8 in c:\users\anil\downloads\messmetrics\backend-fastapi\.venv\lib\site-packages (from anyio<5,>=4.10.0->openai) (3.20)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2.12.0->openai)
  Obtaining dependency information for httpcore2==2.13.1 from https://files.pythonhosted.org/packages/09/ba/a4568248771ce81957bfb7cc600264a40fbcda092391ee1c415c50be4bea/httpcore2-2.13.1-py3-none-any.whl.metadata
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2.12.0->openai)
  Obtaining dependency information for truststore>=0.10 from https://files.pythonhosted.org/packages/51/e9/3a7820be2bb0fe53b6bc9c3be26d3d1158004e4c3ab953aa6840b955b1e9/truststore-0.10.5-py3-none-any.whl.metadata
  Downloading truststore-0.10.5-py3-none-any.whl.metadata (4.5 kB)
Collecting h11>=0.16 (from httpcore2==2.13.1->httpx2<3,>=2.12.0->openai)
  Obtaining dependency information for h11>=0.16 from https://files.pythonhosted.org/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl.metadata
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai)
  Obtaining dependency information for annotated-types>=0.6.0 from https://files.pythonhosted.org/packages/99/91/8acff4f5e50511b911bbccb72b8628a49c68ce14148cd9f6431094859a90/annotated_types-0.8.0-py3-none-any.whl.metadata
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.50.1 (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai)
  Obtaining dependency information for pydantic-core==2.50.1 from https://files.pythonhosted.org/packages/c5/17/8bbd530b8659e9d963f5b16f6cb8e159f4cd174b4d6304e48969ab12dba8/pydantic_core-2.50.1-cp312-cp312-win_amd64.whl.metadata
  Downloading pydantic_core-2.50.1-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Collecting typing-inspection>=0.4.4 (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai)
  Obtaining dependency information for typing-inspection>=0.4.4 from https://files.pythonhosted.org/packages/67/81/4add07e5172b7ac40d8ed5ff580409a7801a4fe26d529bdd915401dabfbe/typing_inspection-0.4.4-py3-none-any.whl.metadata
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Downloading openai-3.31.0-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
    --------------------------------------- 0.0/2.2 MB 87.5 kB/s eta 0:00:26
   - -------------------------------------- 0.1/2.2 MB 87.4 kB/s eta 0:00:25
   -- ------------------------------------- 0.1/2.2 MB 139.5 kB/s eta 0:00:16
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.1/2.2 MB 173.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.2/2.2 MB 94.6 kB/s eta 0:00:23
   -- ------------------------------------- 0.2/2.2 MB 94.6 kB/s eta 0:00:23
   --- ------------------------------------ 0.2/2.2 MB 101.8 kB/s eta 0:00:21
   --- ------------------------------------ 0.2/2.2 MB 110.2 kB/s eta 0:00:19
   ---- ----------------------------------- 0.2/2.2 MB 125.1 kB/s eta 0:00:17
   ----- ---------------------------------- 0.3/2.2 MB 174.0 kB/s eta 0:00:12
   ------- -------------------------------- 0.4/2.2 MB 216.5 kB/s eta 0:00:09
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.4/2.2 MB 235.3 kB/s eta 0:00:08
   -------- ------------------------------- 0.5/2.2 MB 208.8 kB/s eta 0:00:09
   -------- ------------------------------- 0.5/2.2 MB 218.5 kB/s eta 0:00:09
   --------- ------------------------------ 0.5/2.2 MB 235.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.2 MB 235.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.2 MB 235.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.2 MB 235.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.5/2.2 MB 235.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.6/2.2 MB 228.3 kB/s eta 0:00:08
   ----------- ---------------------------- 0.6/2.2 MB 251.5 kB/s eta 0:00:07
   ------------ --------------------------- 0.7/2.2 MB 267.0 kB/s eta 0:00:06
   ------------ --------------------------- 0.7/2.2 MB 275.7 kB/s eta 0:00:06
   ------------ --------------------------- 0.7/2.2 MB 275.7 kB/s eta 0:00:06
   ------------- -------------------------- 0.7/2.2 MB 268.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.7/2.2 MB 271.2 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   ------------- -------------------------- 0.8/2.2 MB 279.3 kB/s eta 0:00:06
   -------------- ------------------------- 0.8/2.2 MB 264.8 kB/s eta 0:00:06
   --------------- ------------------------ 0.8/2.2 MB 274.1 kB/s eta 0:00:06
   --------------- ------------------------ 0.9/2.2 MB 280.0 kB/s eta 0:00:05
   --------------- ------------------------ 0.9/2.2 MB 280.0 kB/s eta 0:00:05
   --------------- ------------------------ 0.9/2.2 MB 276.2 kB/s eta 0:00:05
   ---------------- ----------------------- 0.9/2.2 MB 278.6 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.2 MB 290.3 kB/s eta 0:00:05
   ------------------ --------------------- 1.0/2.2 MB 301.5 kB/s eta 0:00:05
   ------------------ --------------------- 1.1/2.2 MB 309.5 kB/s eta 0:00:04
   ------------------- -------------------- 1.1/2.2 MB 318.7 kB/s eta 0:00:04
   ------------------- -------------------- 1.1/2.2 MB 318.7 kB/s eta 0:00:04
   -------------------- ------------------- 1.1/2.2 MB 320.4 kB/s eta 0:00:04
   -------------------- ------------------- 1.1/2.2 MB 321.9 kB/s eta 0:00:04
   -------------------- ------------------- 1.1/2.2 MB 321.9 kB/s eta 0:00:04
   --------------------- ------------------ 1.2/2.2 MB 323.4 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.2 MB 349.8 kB/s eta 0:00:03
   -------------------------- ------------- 1.5/2.2 MB 386.7 kB/s eta 0:00:03
   -------------------------- ------------- 1.5/2.2 MB 394.3 kB/s eta 0:00:02
   --------------------------- ------------ 1.5/2.2 MB 396.4 kB/s eta 0:00:02
   --------------------------- ------------ 1.5/2.2 MB 398.0 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 401.7 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 396.3 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 396.3 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.2 MB 399.8 kB/s eta 0:00:02
   ----------------------------- ---------- 1.7/2.2 MB 404.3 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 407.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 407.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 401.5 kB/s eta 0:00:02
   ------------------------------ --------- 1.7/2.2 MB 401.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.2 MB 409.3 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 411.9 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 390.5 kB/s eta 0:00:02
   -------------------------------- ------- 1.8/2.2 MB 391.0 kB/s eta 0:00:02
   --------------------------------- ------ 1.9/2.2 MB 392.8 kB/s eta 0:00:01
   --------------------------------- ------ 1.9/2.2 MB 389.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.9/2.2 MB 393.6 kB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 423.6 kB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 452.9 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 452.1 kB/s eta 0:00:00
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
   ---------------------------------------- 0.0/132.1 kB ? eta -:--:--
   ------------ -------------------------- 41.0/132.1 kB 991.0 kB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   --------------------------- ------------ 92.2/132.1 kB 1.1 MB/s eta 0:00:01
   -------------------------------- ----- 112.6/132.1 kB 142.6 kB/s eta 0:00:01
   -------------------------------------- 132.1/132.1 kB 162.5 kB/s eta 0:00:00
Downloading httpx2-2.13.1-py3-none-any.whl (95 kB)
   ---------------------------------------- 0.0/95.6 kB ? eta -:--:--
   ------------ --------------------------- 30.7/95.6 kB 660.6 kB/s eta 0:00:01
   ------------------------- -------------- 61.4/95.6 kB 825.8 kB/s eta 0:00:01
   ---------------------------------------- 95.6/95.6 kB 783.1 kB/s eta 0:00:00
Downloading httpcore2-2.13.1-py3-none-any.whl (83 kB)
   ---------------------------------------- 0.0/83.4 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/83.4 kB ? eta -:--:--
   ---------------------------------------- 83.4/83.4 kB 1.6 MB/s eta 0:00:00
Downloading jiter-0.17.0-cp312-cp312-win_amd64.whl (227 kB)
   ---------------------------------------- 0.0/227.4 kB ? eta -:--:--
   ----- ---------------------------------- 30.7/227.4 kB 1.3 MB/s eta 0:00:01
   -------------- ------------------------- 81.9/227.4 kB 1.2 MB/s eta 0:00:01
   --------------------- ------------------ 122.9/227.4 kB 1.0 MB/s eta 0:00:01
   ------------------------------ --------- 174.1/227.4 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------  225.3/227.4 kB 1.1 MB/s eta 0:00:01
   -------------------------------------- 227.4/227.4 kB 991.5 kB/s eta 0:00:00
Downloading pydantic-2.14.1-py3-none-any.whl (488 kB)
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/488.1 kB ? eta -:--:--
   -- ------------------------------------ 30.7/488.1 kB 660.6 kB/s eta 0:00:01
   -- ------------------------------------ 30.7/488.1 kB 660.6 kB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   -------------- ------------------------- 174.1/488.1 kB 1.2 MB/s eta 0:00:01
   --------------- ---------------------- 204.8/488.1 kB 479.2 kB/s eta 0:00:01
   ------------------- ------------------ 256.0/488.1 kB 542.5 kB/s eta 0:00:01
   --------------------- ---------------- 276.5/488.1 kB 568.9 kB/s eta 0:00:01
   --------------------- ---------------- 276.5/488.1 kB 568.9 kB/s eta 0:00:01
   --------------------- ---------------- 276.5/488.1 kB 568.9 kB/s eta 0:00:01
   --------------------- ---------------- 276.5/488.1 kB 568.9 kB/s eta 0:00:01
   --------------------- ---------------- 276.5/488.1 kB 568.9 kB/s eta 0:00:01
   ----------------------- -------------- 307.2/488.1 kB 413.6 kB/s eta 0:00:01
   -------------------------- ----------- 337.9/488.1 kB 419.6 kB/s eta 0:00:01
   --------------------------- ---------- 358.4/488.1 kB 436.8 kB/s eta 0:00:01
   ------------------------------ ------- 389.1/488.1 kB 433.0 kB/s eta 0:00:01
   ------------------------------ ------- 389.1/488.1 kB 433.0 kB/s eta 0:00:01
   -------------------------------- ----- 419.8/488.1 kB 423.1 kB/s eta 0:00:01
   ------------------------------------ - 471.0/488.1 kB 460.8 kB/s eta 0:00:01
   -------------------------------------- 488.1/488.1 kB 470.8 kB/s eta 0:00:00
Downloading pydantic_core-2.50.1-cp312-cp312-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
    --------------------------------------- 0.0/2.2 MB 1.3 MB/s eta 0:00:02
   - -------------------------------------- 0.1/2.2 MB 1.1 MB/s eta 0:00:02
   - -------------------------------------- 0.1/2.2 MB 975.2 kB/s eta 0:00:03
   - -------------------------------------- 0.1/2.2 MB 655.4 kB/s eta 0:00:04
   -- ------------------------------------- 0.1/2.2 MB 654.9 kB/s eta 0:00:04
   --- ------------------------------------ 0.2/2.2 MB 748.1 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/2.2 MB 765.3 kB/s eta 0:00:03
   ---- ----------------------------------- 0.3/2.2 MB 780.5 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.2 MB 824.9 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.2 MB 824.9 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.2 MB 824.9 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.2 MB 824.9 kB/s eta 0:00:03
   ----- ---------------------------------- 0.3/2.2 MB 824.9 kB/s eta 0:00:03
   ------ --------------------------------- 0.3/2.2 MB 537.2 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.2 MB 540.7 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.2 MB 540.7 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.2 MB 540.7 kB/s eta 0:00:04
   ------ --------------------------------- 0.3/2.2 MB 540.7 kB/s eta 0:00:04

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:

from openai import OpenAI

client = OpenAI(
    base_url="http://127.0.0.1:11434/v1",
    api_key="dummy_key"
)

response = client.chat.completions.create(
    model="qwen3:4b",
    messages=[
        {
            "role": "user",
            "content": "Hello LLM"
        }
    ]
)

print(response.choices[0].message.content)

KeyboardInterrupt:

In [68]:
import requests

url = "https://api.calorieninjas.com/v1/nutrition"

params = {
    "query": "10 oz onion and a tomato"
}

headers = {
    "X-Api-Key": "awJWYcYr4okypbo2qZ8lag==WmaDLqvIbCCxjbWL"
}

response = requests.get(
    url,
    params=params,
    headers=headers
)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(response.status_code, response.text)

{'items': [{'name': 'onion', 'calories': 126.7, 'serving_size_g': 283.495, 'fat_total_g': 0.5, 'fat_saturated_g': 0.1, 'protein_g': 3.9, 'sodium_mg': 8, 'potassium_mg': 99, 'cholesterol_mg': 0, 'carbohydrates_total_g': 28.6, 'fiber_g': 4.0, 'sugar_g': 13.3}, {'name': 'tomato', 'calories': 18.2, 'serving_size_g': 100.0, 'fat_total_g': 0.2, 'fat_saturated_g': 0.0, 'protein_g': 0.9, 'sodium_mg': 4, 'potassium_mg': 23, 'cholesterol_mg': 0, 'carbohydrates_total_g': 3.9, 'fiber_g': 1.2, 'sugar_g': 2.6}]}

In [71]:
res=response.text

In [77]:
import json
obj=json.loads(res)

In [84]:
obj['items'][0]['name']

'onion'

In [92]:
n = [
        "calories",
        "protein_g",
        "fat_total_g",
        "fat_saturated_g",
        "carbohydrates_total_g",
        "fiber_g",
        "sugar_g",
        "sodium_mg",
        "potassium_mg",
        "cholesterol_mg",
        "serving_size_g"
    ]

In [93]:
overall={}
# for k in range(0,len())
type(obj['items'])
for i in n:
    sum=0
    for j in obj['items']:
        sum+=j[i]
    overall[i]=sum

In [94]:
overall

{'calories': 144.9,
 'protein_g': 4.8,
 'fat_total_g': 0.7,
 'fat_saturated_g': 0.1,
 'carbohydrates_total_g': 32.5,
 'fiber_g': 5.2,
 'sugar_g': 15.9,
 'sodium_mg': 12,
 'potassium_mg': 122,
 'cholesterol_mg': 0,
 'serving_size_g': 383.495}

In [95]:
def calculate_calories(age, height, weight, sex, activity):
    # Calculate BMR
    if sex.lower() == "male":
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    elif sex.lower() == "female":
        bmr = 10 * weight + 6.25 * height - 5 * age - 161
    else:
        raise ValueError("sex must be 'male' or 'female'")

    # Calculate TDEE
    activity_factors = {
        "sedentary": 1.2,
        "light": 1.375,
        "moderate": 1.55,
        "very_active": 1.725,
        "extra_active": 1.9
    }

    if activity not in activity_factors:
        raise ValueError("Invalid activity level")

    tdee = bmr * activity_factors[activity]

    return {
        "bmr": round(bmr),
        "maintenance_calories": round(tdee)
    }


result = calculate_calories(
    age=22,
    height=175,
    weight=75,
    sex="male",
    activity="moderate"
)

print(result)

{'bmr': 1739, 'maintenance_calories': 2695}